// AUTO-GENERATED by scripts/generateRecipeIcons.ts — do not edit manually
import { ImageSourcePropType } from 'react-native';

export const RECIPE_ICON_MAP: Record<string, ImageSourcePropType> = {
};
