// ═══════════════════════════════════════════════════════════════════════════════
// scripts/generateRecipeIcons.ts
// Run: npx tsx scripts/generateRecipeIcons.ts
// Requires HF_TOKEN in .env  (get one free at huggingface.co/settings/tokens)
// ═══════════════════════════════════════════════════════════════════════════════
import * as fs from 'fs';
import * as path from 'path';

// ── load .env ────────────────────────────────────────────────────────────────
const envPath = path.join(__dirname, '../.env');
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[key]) process.env[key] = val;
  }
}

const HF_TOKEN = process.env.HF_TOKEN;

// Best pixel-art SDXL finetune available on HF Inference API.
// Change this if you want to experiment with other models.
const MODEL   = 'nerijs/pixel-art-xl';
const API_URL = `https://api-inference.huggingface.co/models/${MODEL}`;

const ASSETS_DIR = path.join(__dirname, '../assets/recipe-icons');
const MAP_PATH   = path.join(__dirname, '../src/components/recipeIconMap.ts');

// ── helpers ──────────────────────────────────────────────────────────────────
function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }
function randomBetween(minSec: number, maxSec: number) {
  return (minSec + Math.random() * (maxSec - minSec)) * 1000;
}

async function generateIcon(recipeName: string, recipeId: string): Promise<void> {
  const prompt =
    `pixel art RPG game food icon of ${recipeName}, ` +
    `8-bit retro style, game item icon, vibrant warm colors, ` +
    `centered on dark background, simple clean design, no text`;

  const negativePrompt =
    'blurry, low quality, text, watermark, signature, realistic, ' +
    'photograph, 3d render, multiple items';

  // Retry up to 4 times — first attempt may trigger a cold model load (503)
  for (let attempt = 1; attempt <= 4; attempt++) {
    const res = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${HF_TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        inputs: prompt,
        parameters: {
          negative_prompt: negativePrompt,
          width: 512,
          height: 512,
          num_inference_steps: 25,
          guidance_scale: 7.5,
        },
      }),
    });

    if (res.status === 503) {
      const json: any = await res.json().catch(() => ({}));
      const waitSec = Math.max(json.estimated_time ?? 30, 20);
      console.log(`  Model loading (attempt ${attempt}/4), waiting ${waitSec}s...`);
      await sleep(waitSec * 1000);
      continue;
    }

    if (res.status === 429) {
      console.log(`  Rate limited, waiting 60s...`);
      await sleep(60_000);
      continue;
    }

    if (!res.ok) {
      throw new Error(`HTTP ${res.status}: ${await res.text()}`);
    }

    const buffer = Buffer.from(await res.arrayBuffer());
    if (buffer.length < 1000) {
      throw new Error(`Response too small (${buffer.length} bytes) — likely an error`);
    }

    const outPath = path.join(ASSETS_DIR, `${recipeId}.png`);
    fs.writeFileSync(outPath, buffer);
    console.log(`  ✓ ${recipeId}: ${recipeName} (${Math.round(buffer.length / 1024)}KB)`);
    return;
  }

  throw new Error('Max retries exceeded');
}

function rebuildMapFile() {
  const files = fs.existsSync(ASSETS_DIR)
    ? fs.readdirSync(ASSETS_DIR).filter(f => f.endsWith('.png') && !f.startsWith('test_'))
    : [];
  const ids = files.map(f => f.replace('.png', '')).sort();

  const requires = ids
    .map(id => `  '${id}': require('../../assets/recipe-icons/${id}.png'),`)
    .join('\n');

  const content =
    `// AUTO-GENERATED by scripts/generateRecipeIcons.ts — do not edit manually\n` +
    `import { ImageSourcePropType } from 'react-native';\n\n` +
    `export const RECIPE_ICON_MAP: Record<string, ImageSourcePropType> = {\n` +
    `${requires}\n` +
    `};\n`;

  fs.writeFileSync(MAP_PATH, content);
  console.log(`\n  Map file updated: ${ids.length} icons`);
}

// ── main ─────────────────────────────────────────────────────────────────────
async function main() {
  if (!HF_TOKEN) {
    console.error('ERROR: HF_TOKEN not set. Add it to .env');
    console.error('Get a free token at: https://huggingface.co/settings/tokens');
    process.exit(1);
  }

  if (!fs.existsSync(ASSETS_DIR)) fs.mkdirSync(ASSETS_DIR, { recursive: true });

  const recipes: { id: string; name: string }[] =
    require('../src/data/curatedRecipesSeed.json');

  const pending = recipes.filter(r => {
    const exists = fs.existsSync(path.join(ASSETS_DIR, `${r.id}.png`));
    if (exists) console.log(`  skip ${r.id} (already done)`);
    return !exists;
  });

  console.log(`\nGenerating ${pending.length} icons (${recipes.length - pending.length} already done)\n`);
  if (pending.length === 0) { rebuildMapFile(); return; }

  for (let i = 0; i < pending.length; i++) {
    const recipe = pending[i];
    try {
      await generateIcon(recipe.name, recipe.id);
    } catch (err) {
      console.error(`  ✗ ${recipe.id}: ${err}`);
    }

    if (i < pending.length - 1) {
      const waitMs = randomBetween(45, 75); // 45–75s between requests on free tier
      const remaining = pending.length - i - 1;
      console.log(`  Waiting ${Math.round(waitMs / 1000)}s... (${remaining} left)\n`);
      await sleep(waitMs);
    }
  }

  rebuildMapFile();
  console.log('\nAll done. Reload Expo to see new icons.');
}

main().catch(err => { console.error(err); process.exit(1); });
